version: "3.9"

services:
  tour-world:
    build: .
    ports:
      - "5000:5000" # Map container port 3000 to host port 3000
    volumes:
      - ./:/app # Mount your project directory to /app inside the container

volumes:
  tour-world: # Optional volume to persist data (modify as needed)
